services:
  - type: web
    name: pulsemon-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: MONGO_URI
        value: your_mongo_uri
      - key: SLACK_WEBHOOK
        value: your_slack_webhook
      - key: TELEGRAM_TOKEN
        value: your_bot_token
      - key: TELEGRAM_CHAT_ID
        value: your_telegram_chat_id

